repos:
- repo: local
  hooks:
    - id: asciidoctor
      name: asciidoctor
      entry: asciidoctor-pdf OG_Format.adoc
      language: system
      always_run: true

- repo: local
  hooks:
    - id: asciidoctor-git
      name: asciidoctor-git
      entry: git add OG_Format.pdf
      language: system
      always_run: true

